apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo-ms-user-service
  labels:
    environment: production
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: demo-ms-user-service
          image: user_service
          ports:
            - containerPort: 1331
